[project]
name = "glyph"
uuid = "cegyya7j6lsn78ftvos7pv5me"
version = "0.1.0"
description = "Error-correction codes"
repository = "https://github.com/chaseruskin/glyph.git"
public = ["rtl"]
keywords = ["ecc", "code"]

[dependencies]
steel = "0.1"
