name: Pipeline
on: push

jobs:
  test:
    runs-on: ubuntu-22.04
    container:
      image: chaseruskin/groovy-guitar:latest
    steps:
      - name: Fetch repository
        uses: actions/checkout@v4

      - name: Log tools
        run: bash /etc/tools

      - name: Configure Orbit
        run: just configure

      - name: Test software
        run: just test-sw

      - name: Run simulations
        run: just test

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test
          path: |
            target/goku/results
