name: Pipeline
on: push

jobs:
  test:
    runs-on: ubuntu-22.04
    container:
      image: chaseruskin/groovy-guitar:latest
    steps:
      - name: Fetch repository
        uses: actions/checkout@v4

      - name: Log tools
        run: bash /etc/tools

      - name: Configure Orbit
        run: |
          pip install git+https://github.com/chaseruskin/aquila.git
          orbit config --push include="$(aquila-config --config-path)"

      - name: Test parity
        run: |
          orbit test --target ghdl --dut parity -- -g SIZE=8 -g EVEN_PARITY=false
          orbit test --target ghdl --dut parity -- -g SIZE=5 -g EVEN_PARITY=true

      - name: Test hamming encoder
        run: |
          orbit test --target ghdl --dut hamm_enc -- -g PARITY_BITS=2
          orbit test --target ghdl --dut hamm_enc -- -g PARITY_BITS=4
          orbit test --target ghdl --dut hamm_enc -- -g PARITY_BITS=5

      - name: Test hamming decoder
        run: |
          orbit test --target ghdl --dut hamm_dec -- -g PARITY_BITS=2
          orbit test --target ghdl --dut hamm_dec -- -g PARITY_BITS=4
          orbit test --target ghdl --dut hamm_dec -- -g PARITY_BITS=5

  build:
    runs-on: ubuntu-22.04
    container:
      image: chaseruskin/quiet-quartet:latest
    steps:
      - name: Fetch repository
        uses: actions/checkout@v4

      - name: Log tools
        run: bash /etc/tools

      - name: Configure Orbit
        run: |
          pip install git+https://github.com/chaseruskin/aquila.git
          orbit config --push include="$(aquila-config --config-path)"

      - name: Synthesize hamming encoder
        run: orbit build --target quartz --top hamm_enc -- -g PARITY_BITS=3 -r bit

      - name: Save reports
        uses: actions/upload-artifact@v4
        with:
          name: build-reports
          path: |
            target/quartz/*.summary
            target/quartz/*.rpt
            target/quartz/*.pof
            target/quartz/*.sof