name: Pipeline
on: push

jobs:
  test:
    runs-on: ubuntu-22.04
    container:
      image: chaseruskin/groovy-guitar:latest
    steps:
      - name: Fetch repository
        uses: actions/checkout@v4

      - name: Log tools
        run: bash /etc/tools

      - name: Configure Orbit
        run: |
          pip install git+https://github.com/chaseruskin/aquila.git
          orbit config --push include="$(aquila-config --config-path)"

      - name: Test parity
        run: |
          orbit test --target ghdl --dut parity -- -r com -g W=8 -g EVEN=false
          orbit test --target ghdl --dut parity -- -r com -g W=5 -g EVEN=true

      - name: Test Hamming encoder
        run: |
          orbit test --target ghdl --dut hamming_enc -- -r com -g K=4
          orbit test --target ghdl --dut hamming_enc -- -r com -g K=32
          orbit test --target ghdl --dut hamming_enc -- -r com -g K=64

      - name: Test Hamming decoder
        run: |
          orbit test --target ghdl --dut hamming_dec -- -r com -g K=4
          orbit test --target ghdl --dut hamming_dec -- -r com -g K=32
          orbit test --target ghdl --dut hamming_dec -- -r com -g K=64

  build:
    runs-on: ubuntu-22.04
    container:
      image: chaseruskin/quiet-quartet:latest
    steps:
      - name: Fetch repository
        uses: actions/checkout@v4

      - name: Log tools
        run: bash /etc/tools

      - name: Configure Orbit
        run: |
          pip install git+https://github.com/chaseruskin/aquila.git
          orbit config --push include="$(aquila-config --config-path)"

      - name: Build Hamming encoder
        run: orbit build --target quartz --top hamming_enc -- -r bit -g K=4

      - name: Save reports
        uses: actions/upload-artifact@v4
        with:
          name: build-reports
          path: |
            target/quartz/*.summary
            target/quartz/*.rpt
            target/quartz/*.pof
            target/quartz/*.sof